### ISSUE TITLE
Official Scalar package

### ISSUE THREAD

**Issue by hanspagel** [benirave/AspNetCore.Scalar#59]
Hi @benirave! Thank you so much for putting this together! We’re providing an official package for Scalar:

* https://www.nuget.org/packages/AspNetCore.Scalar
* https://github.com/scalar/scalar/tree/main/packages/scalar.aspnetcore

Should we join the forces? Anything you’re missing in the official package? Would love to see you in our Discord, hmu: @hanspagel

**Comment by benirave** [comment]
Hi @hanspagel,

I apologize for the delayed response; I've been quite busy.

I've noticed many changes have been made to the .NET version. Initially, my concern was that the official package relied on the CDN version of Scalar, which prevented it from enforcing the specific Scalar version in use. I can see this has been addressed, although unfortunately, it's not documented very well.

Additionally, the .NET package had minimal tests available, but it seems that has been improved. :)

However, it's worth noting that it still does not support older versions of .NET.

I plan to reach out over Discord sometime next week so we can discuss this further! :)
